# Generated by Django 4.1.3 on 2023-03-03 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0005_khachhang'),
        ('khachhang', '0002_remove_donhang_khachhang_delete_ctdonhang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaydathang', models.DateField()),
                ('httt', models.CharField(max_length=50)),
                ('diachigiaohang', models.CharField(max_length=250)),
                ('tongtien', models.FloatField()),
                ('tamung', models.FloatField()),
                ('conlai', models.FloatField()),
                ('khachhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donhang_khachhang', to='khachhang.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='CTDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soluong', models.PositiveIntegerField(default=1)),
                ('donhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donhang_items', to='khachhang.donhang')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanpham_items', to='Computer.sanpham')),
            ],
        ),
    ]
