# Generated by Django 4.1.3 on 2023-02-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KHACHHANG',
        ),
    ]
