# Generated by Django 4.1.3 on 2023-02-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0002_delete_khachhang'),
    ]

    operations = [
        migrations.CreateModel(
            name='KHACHHANG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_kh', models.CharField(max_length=250)),
                ('gioi_tinh', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('ngay_sinh', models.DateField()),
                ('dia_chi', models.CharField(max_length=500)),
                ('dien_thoai', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mat_khau', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
