# Generated by Django 4.1.3 on 2023-02-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0003_khachhang'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KHACHHANG',
        ),
    ]
