# Generated by Django 4.1.3 on 2023-03-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0004_delete_khachhang'),
    ]

    operations = [
        migrations.CreateModel(
            name='KHACHHANG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('confirm', models.CharField(max_length=250)),
                ('fullname', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
