# Generated by Django 4.1.3 on 2023-03-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0005_khachhang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lienhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('sdt', models.CharField(max_length=20, null=True)),
                ('chude', models.CharField(max_length=264)),
                ('noidung', models.TextField()),
            ],
        ),
    ]
